# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.define "gitlab" do |gitlab|
    gitlab.vm.network "forwarded_port", guest: 22, host: 2202, host_ip: "0.0.0.0"
    gitlab.vm.network "forwarded_port", guest: 80, host: 7070, host_ip: "0.0.0.0"
    gitlab.vm.network "private_network", ip: "192.168.50.40"
    gitlab.vm.synced_folder "gitlab/", "/etc/gitlab"
    gitlab.vm.box = "bento/ubuntu-18.04"
  end
end
